name: tdcs-caps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.11
  - pip
  - pip:
    - numpy==1.24.3
    - scipy==1.15.3
    - pandas==2.2.3
    - matplotlib==3.10.3
    - seaborn==0.13.2
    - nibabel==5.3.2
    - nilearn==0.13.1
    - scikit-learn==1.7.2
    - brainspace==0.1.22
    - brainstat==0.5.2
    - joypy==0.2.6
    - tqdm==4.67.3
    - termcolor==3.2.0
    - python-dotenv==1.2.1
